product_key: chef-server

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-server-notify

github:
  enforce_workflow: true
  maintainer_group: chef/chef-server-maintainers
